POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "birthDate": "2000-01-01",
  "passingDate": "null"
}

### GetUser
GET http://localhost:3000/users/0x532FA5d2f03D8A8D9ec1e14B2F7b01Ef8D85809c

### UpdateUser
PUT http://localhost:3000/users/0x532FA5d2f03D8A8D9ec1e14B2F7b01Ef8D85809c
Content-Type: application/json

{
  "email": "updateduser@example.com"
}

### DeleteUser
DELETE http://localhost:3000/users/0x82D0c8b50230b5565EF68a656F8bF75465A1bcd0